# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18202a5c61ec004447954cdba8a487ae0b3664b4803dd5255677c1fe18856968b4faeeaa7636b5e442be12b85258f20c98ce72b3b82f9e9bff79262d38df18f7

test:
  secret_key_base: 2898a393f6217a8a364e9a8f1385c9b2edfe889967af17366aba8b7ff920a2884141fe021211edbc21e0c817949911e169191a6d9135614e93f2c565bbe91fce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
